-- 1% Better action library seed. Repeatable: on conflict (title) do nothing.
-- Re-running never duplicates actions and never touches user data.

insert into public.actions
  (title, description, category, sub_category, estimated_minutes, difficulty,
   required_energy, mood_tags, situation_tags, base_xp, active)
values
('Take Five Slow Breaths', 'Take five slow breaths and focus only on your breathing.', 'wellbeing', 'breathing', 2, 1, 'low', '{stressed,low}'::text[], '{stress,school,work}'::text[], 10, true),
('Breathe in a Box', 'Breathe in for 4, hold for 4, out for 4, rest for 4. Repeat four times.', 'wellbeing', 'breathing', 3, 1, 'low', '{stressed,low}'::text[], '{stress,school,work}'::text[], 10, true),
('Try the 4-7-8 Breath', 'Breathe in for 4 seconds, hold for 7, exhale slowly for 8. Repeat four times.', 'wellbeing', 'breathing', 4, 2, 'low', '{stressed}'::text[], '{stress,work,school}'::text[], 10, true),
('Breathe with Your Belly', 'Place a hand on your belly and breathe so your hand rises and falls slowly.', 'wellbeing', 'breathing', 3, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Exhale Twice as Long', 'For two minutes, make each exhale twice as long as your inhale.', 'wellbeing', 'breathing', 2, 1, 'low', '{stressed,okay}'::text[], '{stress,work}'::text[], 10, true),
('Listen to Your Breath', 'Close your eyes and listen to the sound of your own breathing for one minute.', 'wellbeing', 'breathing', 2, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Hum to Soothe', 'Exhale while humming softly. Feel the vibration calm your chest.', 'wellbeing', 'breathing', 3, 2, 'low', '{stressed,low}'::text[], '{stress,loneliness}'::text[], 10, true),
('Count Ten Slow Breaths', 'Count ten breaths, slow and even, without rushing any of them.', 'wellbeing', 'breathing', 4, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Name Five Things You See', 'Look around and name five things you can see right now.', 'wellbeing', 'grounding', 2, 1, 'low', '{stressed,low}'::text[], '{stress,other}'::text[], 10, true),
('Feel Three Things', 'Notice three physical sensations: the chair, the floor, the air on your skin.', 'wellbeing', 'grounding', 2, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Use the 5-4-3-2-1 Senses', 'Name 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste.', 'wellbeing', 'grounding', 4, 2, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Plant Your Feet', 'Stand or sit, press both feet into the ground, and notice the pressure for a minute.', 'wellbeing', 'grounding', 1, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Touch Something Textured', 'Find a textured object and run your fingers over it slowly, paying full attention.', 'wellbeing', 'grounding', 2, 1, 'low', '{stressed}'::text[], '{stress,other}'::text[], 10, true),
('Take a Cold Sip', 'Drink a glass of cold water slowly, noticing the temperature.', 'wellbeing', 'grounding', 2, 1, 'low', '{stressed,okay}'::text[], '{stress}'::text[], 10, true),
('Say the Date Out Loud', 'Say today''s date, the day, and one true fact about this moment out loud.', 'wellbeing', 'grounding', 1, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Name Three Sounds Around You', 'Stop and name three sounds you can hear right now.', 'wellbeing', 'grounding', 2, 1, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Scan Your Body Quickly', 'From head to toe, notice where you hold tension for 20 seconds each spot.', 'wellbeing', 'relaxation', 5, 2, 'low', '{stressed,low}'::text[], '{stress}'::text[], 10, true),
('Tense and Release Your Shoulders', 'Shrug your shoulders up for 5 seconds, then drop and release. Repeat three times.', 'wellbeing', 'relaxation', 3, 1, 'low', '{stressed,low}'::text[], '{stress,work}'::text[], 10, true),
('Soften Your Jaw', 'Unclench your jaw, lower your tongue, and let your face relax.', 'wellbeing', 'relaxation', 1, 1, 'low', '{stressed}'::text[], '{stress,work}'::text[], 10, true),
('Progressive Muscle Relax', 'Tense each muscle group for 5 seconds, then release, moving down your body.', 'wellbeing', 'relaxation', 8, 3, 'low', '{stressed,low}'::text[], '{stress}'::text[], 15, true),
('Rest Your Eyes', 'Close your eyes and let them rest for two full minutes.', 'wellbeing', 'relaxation', 2, 1, 'low', '{low,stressed}'::text[], '{stress,school,work}'::text[], 10, true),
('Do Nothing for Three Minutes', 'Set a timer for three minutes and simply sit without a task.', 'wellbeing', 'relaxation', 3, 1, 'low', '{stressed,low}'::text[], '{stress,motivation}'::text[], 10, true),
('Loosen Your Hands', 'Shake out both hands loosely for thirty seconds and notice how it feels.', 'wellbeing', 'relaxation', 1, 1, 'low', '{stressed}'::text[], '{work,school}'::text[], 10, true),
('Write One Thing That Went Well', 'Write down one small thing that went well today.', 'wellbeing', 'gratitude', 3, 1, 'low', '{low,okay}'::text[], '{motivation,loneliness}'::text[], 10, true),
('Say Thanks for Three Small Things', 'Mentally thank three small things: hot water, daylight, a good chair.', 'wellbeing', 'gratitude', 3, 1, 'low', '{low,okay}'::text[], '{motivation}'::text[], 10, true),
('Text a Simple Thank You', 'Send a short thank-you message to someone who helped you recently.', 'wellbeing', 'gratitude', 5, 2, 'low', '{good,okay}'::text[], '{friends,family}'::text[], 10, true),
('Recall a Kind Memory', 'Remember one kind moment from the past week and replay it in detail.', 'wellbeing', 'gratitude', 4, 2, 'low', '{low,okay}'::text[], '{loneliness,motivation}'::text[], 10, true),
('List What You Have Today', 'List three things you have right now that you sometimes take for granted.', 'wellbeing', 'gratitude', 4, 1, 'low', '{low,okay}'::text[], '{motivation,money}'::text[], 10, true),
('Thank Someone Out Loud', 'Tell someone face to face one specific thing you appreciate about them.', 'wellbeing', 'gratitude', 3, 3, 'medium', '{good}'::text[], '{friends,family}'::text[], 15, true),
('Soothe Yourself with Kind Words', 'Say to yourself: ''This is hard, and I''m doing my best.''', 'wellbeing', 'self-soothing', 2, 1, 'low', '{low,stressed}'::text[], '{stress,school,work}'::text[], 10, true),
('Wrap Yourself in a Blanket', 'Wrap a blanket around yourself for a few minutes and breathe slowly.', 'wellbeing', 'self-soothing', 5, 1, 'low', '{low,stressed}'::text[], '{loneliness,stress}'::text[], 10, true),
('Make a Warm Drink', 'Make a warm drink and hold the cup with both hands, sipping slowly.', 'wellbeing', 'self-soothing', 6, 1, 'low', '{low,okay}'::text[], '{loneliness,stress}'::text[], 10, true),
('Play Something Gentle', 'Play one gentle song you like and give it your full attention.', 'wellbeing', 'self-soothing', 4, 1, 'low', '{low,stressed}'::text[], '{stress,loneliness}'::text[], 10, true),
('Stretch Your Neck Gently', 'Slowly tilt your head side to side, staying soft and easy.', 'wellbeing', 'relaxation', 3, 1, 'low', '{stressed}'::text[], '{work,school}'::text[], 10, true),
('Pick One Task for Today', 'Choose exactly one task that matters and write it down.', 'productivity', 'planning', 3, 1, 'low', '{okay,good}'::text[], '{work,school,motivation}'::text[], 10, true),
('Write a Five-Item To-Do List', 'Write down five tasks, then circle the single most important one.', 'productivity', 'planning', 5, 2, 'low', '{okay,good}'::text[], '{work,school,motivation}'::text[], 10, true),
('Plan Your Top Three', 'Write the three most important things to do today, in order.', 'productivity', 'planning', 5, 2, 'low', '{good,okay}'::text[], '{work,school}'::text[], 10, true),
('Set One Time Block', 'Reserve one 25-minute block for your most important task.', 'productivity', 'planning', 3, 2, 'low', '{okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Write Tomorrow''s Plan Tonight', 'Tonight, write the first task you''ll start with tomorrow.', 'productivity', 'planning', 4, 2, 'low', '{okay,low}'::text[], '{work,school,motivation}'::text[], 10, true),
('Decide the Next Step Only', 'For your biggest task, write down only the very next physical step.', 'productivity', 'planning', 4, 2, 'low', '{low,okay}'::text[], '{motivation,work,school}'::text[], 10, true),
('Break a Task into Three Pieces', 'Take one task you''re avoiding and split it into three small pieces.', 'productivity', 'task breakdown', 5, 3, 'medium', '{low,okay}'::text[], '{motivation,work,school}'::text[], 15, true),
('Start With Two Minutes', 'Spend just two minutes starting the task you''re avoiding.', 'productivity', 'task breakdown', 2, 2, 'low', '{low,okay}'::text[], '{motivation,work,school}'::text[], 10, true),
('Do One Micro-Task', 'Complete the smallest useful piece of your big project.', 'productivity', 'task breakdown', 5, 2, 'low', '{okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Estimate How Long It Really Takes', 'Guess how long your task takes, then check how close you were.', 'productivity', 'task breakdown', 4, 2, 'low', '{good}'::text[], '{work,school}'::text[], 10, true),
('Clear Your Desk of One Thing', 'Put away one thing that is cluttering your workspace.', 'productivity', 'organization', 3, 1, 'low', '{okay,good}'::text[], '{work,school}'::text[], 10, true),
('Close Ten Extra Tabs', 'Close the ten browser tabs you no longer need.', 'productivity', 'organization', 3, 1, 'low', '{good,okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Sort Your Inbox Once', 'Open your inbox and decide the fate of ten messages: reply, file, or delete.', 'productivity', 'organization', 10, 3, 'medium', '{good,okay}'::text[], '{work}'::text[], 15, true),
('Silence Non-Essential Notifications', 'Turn off notifications for apps you don''t need for the next hour.', 'productivity', 'organization', 3, 1, 'low', '{okay}'::text[], '{work,school}'::text[], 10, true),
('Make Your Bed', 'Make your bed before anything else today.', 'productivity', 'organization', 3, 1, 'low', '{okay,good}'::text[], '{motivation,other}'::text[], 10, true),
('Write Your Today Theme', 'Give today a one-word theme, like ''calm'' or ''steady''.', 'productivity', 'planning', 2, 1, 'low', '{okay,low}'::text[], '{motivation}'::text[], 10, true),
('Focus for Ten Minutes', 'Focus on one thing for ten uninterrupted minutes.', 'productivity', 'focus', 10, 2, 'medium', '{good,okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Use the One-Tab Rule', 'Work on one tab, one window, one task for 20 minutes.', 'productivity', 'focus', 20, 3, 'medium', '{good}'::text[], '{work,school}'::text[], 15, true),
('Turn Off Your Phone', 'Switch your phone to airplane mode for 30 minutes and do one thing.', 'productivity', 'focus', 30, 3, 'medium', '{good,okay}'::text[], '{work,school,motivation}'::text[], 15, true),
('Try the Pomodoro First Round', 'Set a 25-minute timer, work on one task, then take a 5-minute break.', 'productivity', 'focus', 30, 3, 'medium', '{good}'::text[], '{work,school}'::text[], 15, true),
('Move Your Phone to Another Room', 'Leave your phone in another room for the next 30 minutes.', 'productivity', 'focus', 30, 2, 'low', '{good,okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Write One Paragraph', 'Write one paragraph toward the thing you keep postponing.', 'productivity', 'focus', 8, 3, 'medium', '{low,okay}'::text[], '{motivation,work,school}'::text[], 15, true),
('Review Your Notes for Five Minutes', 'Read through today''s or yesterday''s notes for five minutes.', 'study', 'revision', 5, 2, 'low', '{good,okay}'::text[], '{school}'::text[], 10, true),
('Summarise One Page in One Sentence', 'Summarise one page of notes into a single sentence.', 'study', 'revision', 5, 3, 'medium', '{okay}'::text[], '{school}'::text[], 15, true),
('Quiz Yourself on Three Facts', 'Cover your notes and recall three key facts from memory.', 'study', 'revision', 5, 3, 'medium', '{good,okay}'::text[], '{school}'::text[], 15, true),
('Teach One Idea Aloud', 'Explain one concept out loud as if teaching a friend.', 'study', 'revision', 6, 3, 'medium', '{good}'::text[], '{school}'::text[], 15, true),
('Re-read One Section Slowly', 'Re-read one section of your material and highlight three key points.', 'study', 'revision', 8, 2, 'low', '{okay}'::text[], '{school}'::text[], 10, true),
('Write Three Revision Questions', 'Write three questions your teacher might ask on the exam.', 'study', 'revision', 8, 3, 'medium', '{okay,good}'::text[], '{school}'::text[], 15, true),
('Make a One-Week Revision Plan', 'Sketch which subjects you''ll revise on each of the next seven days.', 'study', 'exam planning', 10, 3, 'medium', '{good}'::text[], '{school,stress}'::text[], 15, true),
('List What the Exam Covers', 'Write down every topic the exam covers, then mark your weakest two.', 'study', 'exam planning', 8, 3, 'medium', '{okay}'::text[], '{school,stress}'::text[], 15, true),
('Pick Your Weakest Topic', 'Choose your single weakest topic and open its notes.', 'study', 'exam planning', 5, 2, 'low', '{low,okay}'::text[], '{school,stress}'::text[], 10, true),
('Start With the Easy Marks', 'Identify which exam sections earn marks for basic recall and plan to secure them first.', 'study', 'exam planning', 8, 3, 'medium', '{good}'::text[], '{school}'::text[], 15, true),
('Plan Your Exam Morning', 'Write down what you''ll do the morning of the exam, step by step.', 'study', 'exam planning', 6, 2, 'low', '{stressed}'::text[], '{school,stress}'::text[], 10, true),
('Use Flashcards for Three Terms', 'Make flashcards for three terms you keep forgetting.', 'study', 'memory', 8, 2, 'low', '{okay,good}'::text[], '{school}'::text[], 10, true),
('Remember a List With a Story', 'Turn a list you need to memorise into a short, silly story.', 'study', 'memory', 6, 2, 'low', '{good}'::text[], '{school}'::text[], 10, true),
('Test Yourself, Then Check', 'Recall five things from memory, then check your notes for accuracy.', 'study', 'memory', 6, 2, 'medium', '{okay}'::text[], '{school}'::text[], 10, true),
('Space Your Revision', 'Revise one topic today, and schedule the same topic again in two days.', 'study', 'memory', 5, 2, 'low', '{good}'::text[], '{school}'::text[], 10, true),
('Draw a Simple Diagram', 'Turn one concept into a simple diagram from memory.', 'study', 'memory', 7, 3, 'medium', '{good,okay}'::text[], '{school}'::text[], 15, true),
('Rewrite Notes in Your Own Words', 'Rewrite one page of notes using your own words only.', 'study', 'note-taking', 10, 3, 'medium', '{okay}'::text[], '{school}'::text[], 15, true),
('Add One Question to Your Notes', 'Write one question in the margin of your notes that you can''t answer yet.', 'study', 'note-taking', 4, 2, 'low', '{okay}'::text[], '{school}'::text[], 10, true),
('Use the Cornell Layout', 'Split a page into notes and keywords, and fill one section.', 'study', 'note-taking', 10, 3, 'medium', '{good}'::text[], '{school}'::text[], 15, true),
('Highlight Only Three Lines', 'Take a dense page and highlight only the three most important lines.', 'study', 'note-taking', 6, 2, 'low', '{okay}'::text[], '{school}'::text[], 10, true),
('Write One Question Per Section', 'For each section of your notes, write one question the section answers.', 'study', 'note-taking', 8, 3, 'medium', '{good}'::text[], '{school}'::text[], 15, true),
('Message One Friend', 'Send one short message to a friend just to say hi.', 'social', 'message', 3, 2, 'low', '{lonely,okay}'::text[], '{loneliness,friends}'::text[], 10, true),
('Reply to a Stale Message', 'Reply to one message you''ve been meaning to answer.', 'social', 'message', 4, 2, 'low', '{okay}'::text[], '{friends,family}'::text[], 10, true),
('Ask Someone How They Are', 'Text someone and ask how they''re actually doing.', 'social', 'message', 3, 2, 'low', '{good}'::text[], '{friends,loneliness}'::text[], 10, true),
('Send One Voice Note', 'Send a quick voice note to a friend instead of a text.', 'social', 'message', 3, 2, 'low', '{good,okay}'::text[], '{friends,loneliness}'::text[], 10, true),
('Call Someone for Ten Minutes', 'Call a friend or family member and talk for ten minutes.', 'social', 'message', 10, 4, 'high', '{lonely,okay}'::text[], '{loneliness,family,friends}'::text[], 20, true),
('Ask a Friend for Help', 'Ask one person for help with something specific today.', 'social', 'ask-help', 5, 3, 'medium', '{low,okay}'::text[], '{friends,work,school,stress}'::text[], 15, true),
('Tell Someone What You Need', 'Tell one person, clearly, what you need right now.', 'social', 'ask-help', 5, 4, 'medium', '{low,okay}'::text[], '{family,friends,stress}'::text[], 20, true),
('Share How You''re Feeling', 'Tell one trusted person honestly how you''re feeling today.', 'social', 'ask-help', 5, 4, 'medium', '{low,stressed}'::text[], '{friends,family,loneliness}'::text[], 20, true),
('Ask for a Second Opinion', 'Run a small decision by someone you trust.', 'social', 'ask-help', 5, 2, 'low', '{okay}'::text[], '{work,school,friends}'::text[], 10, true),
('Thank a Friend Specifically', 'Tell a friend one specific thing they did that helped you.', 'social', 'thank', 3, 2, 'low', '{good}'::text[], '{friends,family}'::text[], 10, true),
('Leave a Compliment', 'Give one sincere compliment to someone today.', 'social', 'thank', 2, 2, 'low', '{good}'::text[], '{friends,family,work}'::text[], 10, true),
('Send a Message of Encouragement', 'Send one encouraging message to someone who is struggling.', 'social', 'encourage', 4, 2, 'low', '{good}'::text[], '{friends,loneliness}'::text[], 10, true),
('Celebrate Someone''s Win', 'Congratulate someone on a recent win, big or small.', 'social', 'encourage', 3, 1, 'low', '{good}'::text[], '{friends,family,work}'::text[], 10, true),
('Make a Small Offer of Help', 'Offer help to someone for one small thing today.', 'social', 'encourage', 3, 2, 'low', '{good}'::text[], '{friends,family}'::text[], 10, true),
('Invite Someone to Do Something Small', 'Invite a friend to a walk, a coffee, or a short call.', 'social', 'message', 5, 3, 'medium', '{good,okay}'::text[], '{friends,loneliness}'::text[], 15, true),
('Check on Someone Quiet', 'Message someone you haven''t heard from in a while, no agenda.', 'social', 'encourage', 4, 2, 'low', '{good}'::text[], '{friends,loneliness}'::text[], 10, true),
('Introduce Two People', 'Introduce two people who could help each other.', 'social', 'encourage', 5, 3, 'medium', '{good}'::text[], '{work,friends}'::text[], 15, true),
('Say Good Morning to a Neighbour', 'Greet someone in your building or street warmly.', 'social', 'message', 2, 2, 'low', '{good}'::text[], '{loneliness,other}'::text[], 10, true),
('Reconnect With an Old Friend', 'Send one message to an old friend you''ve lost touch with.', 'social', 'message', 4, 3, 'medium', '{okay,lonely}'::text[], '{loneliness,friends}'::text[], 15, true),
('Listen Fully to Someone', 'Give someone your full attention for ten minutes without interrupting.', 'social', 'encourage', 10, 3, 'medium', '{good}'::text[], '{friends,family}'::text[], 15, true),
('Stretch Your Back Slowly', 'Stand up and stretch your back gently for two minutes.', 'physical', 'stretching', 2, 1, 'low', '{okay,stressed}'::text[], '{work,school}'::text[], 10, true),
('Touch Your Toes Five Times', 'Reach for your toes, hold five seconds, and come up slowly. Repeat five times.', 'physical', 'stretching', 5, 2, 'medium', '{okay}'::text[], '{work,school}'::text[], 10, true),
('Roll Your Shoulders', 'Roll your shoulders backward ten times, then forward ten times.', 'physical', 'stretching', 2, 1, 'low', '{stressed}'::text[], '{work,school}'::text[], 10, true),
('Do a Doorway Stretch', 'Place your hands on a doorframe and lean through to open your chest.', 'physical', 'stretching', 3, 2, 'low', '{okay}'::text[], '{work,school}'::text[], 10, true),
('Stretch Your Neck Slowly', 'Gently move your head side to side and chin to chest for a minute.', 'physical', 'stretching', 2, 1, 'low', '{stressed}'::text[], '{work,school}'::text[], 10, true),
('Do a Full-Body Unwind', 'Stretch your neck, shoulders, back, legs, and wrists for five minutes.', 'physical', 'stretching', 5, 2, 'low', '{stressed,okay}'::text[], '{work,school}'::text[], 10, true),
('Walk for Ten Minutes', 'Take a short ten-minute walk outside.', 'physical', 'walking', 10, 2, 'medium', '{low,okay}'::text[], '{stress,loneliness}'::text[], 10, true),
('Walk and Notice the Weather', 'Take a five-minute walk and notice the temperature and light.', 'physical', 'walking', 5, 1, 'low', '{low,okay}'::text[], '{stress}'::text[], 10, true),
('Take the Stairs', 'Use the stairs instead of the lift once today.', 'physical', 'walking', 3, 2, 'medium', '{good}'::text[], '{other,work,school}'::text[], 10, true),
('Walk to a New Spot', 'Walk somewhere you''ve never walked before, even just around the block.', 'physical', 'walking', 15, 3, 'medium', '{good,okay}'::text[], '{loneliness,stress}'::text[], 15, true),
('Walk One Errand on Foot', 'Do one nearby errand on foot instead of by car or bus.', 'physical', 'walking', 15, 3, 'medium', '{good}'::text[], '{other}'::text[], 15, true),
('March in Place for a Minute', 'March in place, lifting knees, for one minute to get your blood moving.', 'physical', 'movement', 1, 1, 'low', '{okay}'::text[], '{work,school,motivation}'::text[], 10, true),
('Do Ten Squats', 'Do ten slow, controlled squats at your own pace.', 'physical', 'movement', 3, 3, 'medium', '{good}'::text[], '{other,work}'::text[], 15, true),
('Dance to One Song', 'Dance freely to one full song, alone if that feels right.', 'physical', 'movement', 4, 2, 'medium', '{good,okay}'::text[], '{motivation,other}'::text[], 10, true),
('Do Five Push-Ups', 'Do five push-ups, on your knees if needed.', 'physical', 'movement', 3, 3, 'medium', '{good}'::text[], '{other}'::text[], 15, true),
('Move Your Body for Two Minutes', 'Jump, stretch, wiggle, or walk for two continuous minutes.', 'physical', 'movement', 2, 2, 'low', '{low,okay}'::text[], '{motivation,work,school}'::text[], 10, true),
('Lift Something Light Ten Times', 'Pick a light weight (or a bottle of water) and lift it ten times each side.', 'physical', 'movement', 3, 2, 'low', '{good}'::text[], '{work,other}'::text[], 10, true),
('Drink a Full Glass of Water', 'Drink a full glass of water slowly, right now.', 'physical', 'water', 2, 1, 'low', '{okay,low}'::text[], '{stress,work,school}'::text[], 10, true),
('Refill Your Water Bottle', 'Fill your water bottle and set it where you''ll see it.', 'physical', 'water', 2, 1, 'low', '{okay}'::text[], '{work,school}'::text[], 10, true),
('Drink Water Before Each Meal', 'Drink a glass of water before each meal today.', 'physical', 'water', 2, 1, 'low', '{good}'::text[], '{other}'::text[], 10, true),
('Swap One Drink for Water', 'Swap your next sugary or caffeinated drink for water.', 'physical', 'water', 1, 2, 'low', '{good}'::text[], '{other}'::text[], 10, true),
('Close Your Eyes for Five Minutes', 'Lie down, close your eyes, and rest fully for five minutes.', 'physical', 'rest', 5, 1, 'low', '{low,stressed}'::text[], '{stress,work,school}'::text[], 10, true),
('Rest Your Eyes From Screens', 'Look away from every screen for three minutes.', 'physical', 'rest', 3, 1, 'low', '{stressed,okay}'::text[], '{work,school}'::text[], 10, true),
('Take a Ten-Minute Power Nap', 'Nap for no more than ten minutes, then get up and move.', 'physical', 'rest', 10, 2, 'low', '{low}'::text[], '{work,school,stress}'::text[], 10, true),
('Go to Bed a Little Earlier', 'Go to bed twenty minutes earlier than usual tonight.', 'physical', 'rest', 20, 3, 'low', '{low}'::text[], '{stress,school,work}'::text[], 15, true),
('Do Nothing Active for One Hour', 'Give yourself one screen-free hour of true rest this evening.', 'physical', 'rest', 60, 2, 'low', '{low,stressed}'::text[], '{stress}'::text[], 10, true),
('Write Three Lines About Today', 'Write three honest lines about how today has been.', 'reflection', 'journaling', 5, 2, 'low', '{okay,low}'::text[], '{motivation,stress}'::text[], 10, true),
('Write a Free Page', 'Write freely for five minutes without stopping or judging.', 'reflection', 'journaling', 5, 2, 'low', '{low,stressed}'::text[], '{stress,other}'::text[], 10, true),
('Write One Worry and One Hope', 'Write down one worry and one hope for this week.', 'reflection', 'journaling', 5, 2, 'low', '{low,stressed}'::text[], '{stress,school,work}'::text[], 10, true),
('Write a Letter You Won''t Send', 'Write a letter to someone about how you feel. You don''t have to send it.', 'reflection', 'journaling', 10, 3, 'medium', '{low,stressed}'::text[], '{family,friends,relationships}'::text[], 15, true),
('Write About a Happy Moment', 'Describe one happy moment from this week in as much detail as you can.', 'reflection', 'journaling', 8, 2, 'low', '{low,okay}'::text[], '{motivation}'::text[], 10, true),
('Keep a One-Question Journal', 'Answer: ''What would make today a little better?''', 'reflection', 'journaling', 4, 1, 'low', '{okay,low}'::text[], '{motivation}'::text[], 10, true),
('Name Your Feeling Precisely', 'Write the exact word for what you feel right now, beyond ''fine''.', 'reflection', 'feelings', 3, 2, 'low', '{low,stressed}'::text[], '{stress,other}'::text[], 10, true),
('Rate Your Feelings', 'Rate how you feel from 1 to 10, then write why it isn''t lower.', 'reflection', 'feelings', 4, 2, 'low', '{low,okay}'::text[], '{stress}'::text[], 10, true),
('Ask Where It Comes From', 'Pick one strong feeling and write what might be triggering it.', 'reflection', 'feelings', 6, 3, 'medium', '{low,stressed}'::text[], '{stress,family,work}'::text[], 15, true),
('Notice the Feeling in Your Body', 'Write where you feel your current emotion in your body, without judging it.', 'reflection', 'feelings', 4, 2, 'low', '{low,stressed}'::text[], '{stress}'::text[], 10, true),
('Name Three Feelings You Had Today', 'List three different feelings you experienced today.', 'reflection', 'feelings', 3, 2, 'low', '{okay}'::text[], '{other}'::text[], 10, true),
('List What You Can Control', 'Write three things you can control today and one you can''t.', 'reflection', 'control', 5, 2, 'low', '{stressed,low}'::text[], '{stress,school,work,family}'::text[], 10, true),
('Sort Worries Into Two Piles', 'Write your worries in two lists: changeable and not changeable today.', 'reflection', 'control', 6, 3, 'medium', '{stressed}'::text[], '{stress,work,school,money}'::text[], 15, true),
('Pick One Controllable Action', 'Choose one small action within your control and commit to it today.', 'reflection', 'control', 4, 2, 'low', '{okay,low}'::text[], '{motivation,stress}'::text[], 10, true),
('Write Your Boundary', 'Write one boundary you want to set or hold this week.', 'reflection', 'control', 5, 3, 'medium', '{stressed,low}'::text[], '{family,friends,relationships,work}'::text[], 15, true),
('Decide What to Let Go Of', 'Write one thing you will stop trying to control this week.', 'reflection', 'control', 4, 2, 'low', '{stressed,low}'::text[], '{stress,family}'::text[], 10, true),
('Write Tomorrow''s First Step', 'Write the first step you''ll take tomorrow, and when.', 'reflection', 'plan-tomorrow', 4, 2, 'low', '{okay,low}'::text[], '{motivation,school,work}'::text[], 10, true),
('Write One Good Thing About Today', 'Write one thing you want to remember about today.', 'reflection', 'plan-tomorrow', 3, 1, 'low', '{okay,low}'::text[], '{motivation}'::text[], 10, true),
('Plan One Energising Thing', 'Plan one small thing you enjoy into tomorrow.', 'reflection', 'plan-tomorrow', 4, 1, 'low', '{low,okay}'::text[], '{motivation,stress}'::text[], 10, true),
('Set Tomorrow''s Intention', 'Write one intention for how you want tomorrow to feel.', 'reflection', 'plan-tomorrow', 3, 1, 'low', '{okay}'::text[], '{motivation}'::text[], 10, true),
('Preview Tomorrow''s Schedule', 'Write tomorrow''s schedule in three lines: morning, midday, evening.', 'reflection', 'plan-tomorrow', 6, 2, 'low', '{stressed}'::text[], '{school,work,stress}'::text[], 10, true),
('List Three Wins From This Week', 'Write three things you finished or handled this week.', 'reflection', 'achievements', 4, 1, 'low', '{low,okay}'::text[], '{motivation}'::text[], 10, true),
('Write What You Learned', 'Write one lesson you learned from a recent mistake.', 'reflection', 'achievements', 5, 2, 'low', '{okay}'::text[], '{other,work,school}'::text[], 10, true),
('Note How Far You''ve Come', 'Compare where you were a month ago to where you are now.', 'reflection', 'achievements', 6, 2, 'low', '{low,okay}'::text[], '{motivation}'::text[], 10, true),
('Give Yourself Credit', 'Write one thing you did today that took courage or care.', 'reflection', 'achievements', 3, 1, 'low', '{low,okay}'::text[], '{motivation}'::text[], 10, true),
('Write Your Top Five Strengths', 'Write down five strengths you know you have.', 'reflection', 'achievements', 4, 1, 'low', '{low}'::text[], '{motivation,loneliness}'::text[], 10, true)
on conflict (title) do nothing;
